### ISSUE TITLE
Problem with backend option 

### ISSUE THREAD

**Issue by bajrangCoder** [isomorphic-git/lightning-fs#124]
I am creating a wrapper of my fs using lighting fs backend option but I am not able to perform these stuff:
- create file
- write file 
- mkdir etc

And all other operation work well like read, stat, etc...

What should I do to perform these create, write, etc stuff?

**Comment by jcubic** [comment]
Did you implement the required interface for the backend object?

**Comment by bajrangCoder** [comment]
Yes , I have implemented the required things.
And error is related to permission and contains that one IDB superBlock method isn't defined

**Comment by jcubic** [comment]
Do you have the code somewhere online where I can test it? IDB should not be used when using the custom backend. Maybe I made a mistake when added the `db` option (it has the superBlock methods), this is the option to change the internal database for defaultBackend that use IndexedDB.

**Comment by bajrangCoder** [comment]
Here is my backend fs code: https://dpaste.org/CZuO1
And here is how I am using it in my case: https://dpaste.org/SX3oM

And here is screenshot of error:
![Screenshot_20231030-081733](https://github.com/isomorphic-git/lightning-fs/assets/71929976/bc66cded-4bba-45b3-9866-0cd474f618bd)

**Comment by jcubic** [comment]
I was looking at the source code and it seems that saveSuperblock function is needed. The default implementation is just calling flush so send the data to indexedDB if they are buffered.

I don't think it will be a good idea to remove this dependency, I'll update the documentation to include save and load superBlock or maybe change them to `init()` and `flush()` since this is what the implementation is actually doing and superBlock is just implementation details of idexedDB based code.

So for now if you save directly to filesystem you can implementation this method and leave it blank.

**Comment by bajrangCoder** [comment]
thanks it worked!
I have just passed empty :
`saveSuperblock` and `loadSuperblock` in custom backend class.

and i have a question:
is readlink, symlink , lstat is required in isomorphic-git ?
My fs don't have this !

**Comment by jcubic** [comment]
I'm not sure about link but lstat is probbably require for git.status(). You can check this function and see if you will get the error. You can also search the code and see if link functions are used. You can search directly on GitHub.

**Comment by bajrangCoder** [comment]
Yeah , I have checked isomorphic-git src and these are needed and also lstat is needed in clonning repo but 
Unfortunately I don't have lstat , symlink etc on Android internal storage (my fs)

**Comment by jcubic** [comment]
You need to simulate the lstat using some different API like checking if path is file or directory and if it exists. You need to implement same API as in NodeJS.

Check nodejs documentation: https://nodejs.org/api/fs.html#class-fsstats most of the stuff is probably not needed. Check the source code what values are used and implement those. You can also check what are implemented in indexedDB-based defaultBackend.

**Comment by jcubic** [comment]
I will just check if the library work without lstat, I was checking the code, I'm not sure if GitHub showed everything, but fs.stat is used only in unit tests. So if you use isomorphic-git it should work without `fs.stat()`. But I'm not 100% sure.
