### ISSUE TITLE
Origin Private Filesystem (OPFS) support?

### ISSUE THREAD

**Issue by matbee-eth** [isomorphic-git/lightning-fs#125]
Does this project support [OPFS](https://webkit.org/blog/12257/the-file-system-access-api-with-origin-private-file-system/) or does it need to be added?

**Comment by jcubic** [comment]
This project only supports fs created using indexedDB.

**Comment by matbee-eth** [comment]
I took a look last night and noticed that, so I'm working on an OPFS fork, thanks!

**Comment by jcubic** [comment]
You don't need to fork it, you will need to delete everything or implement a custom backend.

**Comment by matbee-eth** [comment]
Incorrect wording, I meant an OPFS implementation. All good!

**Comment by jcubic** [comment]
I understand. Forking will give you no good. You will either implement everything from zero or create a custom OPFS backend, but custom backend is almost like implementing everything from scratch. You need to implement all methods like in NodeJS fs module. I never understood what is the purpose of custom backend. For me it looks like whole new implementation. Maybe without `fs.promises` interface that will be created automatically for you.

**Comment by matbee-eth** [comment]
Yep got it working by simply providing {promises:opfs} to iso-git! Thanks so much!

**Comment by inverted-capital** [comment]
@matbee-eth please may we take a look ?

**Comment by matbee-eth** [comment]
> @matbee-eth please may we take a look ?

Yeah I can post it in its raw state and you can take a look

**Comment by mb21** [comment]
Anybody looked into the pros and cons of using OPFS over [lightning-fs](https://github.com/isomorphic-git/lightning-fs)? What are the performance characteristics ([this article](https://rxdb.info/rx-storage-opfs.html#opfs-performance) seems to imply it's better, but does that apply to the access patterns that are typical to git)? How does multi-threaded access behave (from multiple tabs or workers)?

**Comment by matbee-eth** [comment]
> @matbee-eth please may we take a look ?

I completely forgot about this. I'll carve out some time this week. I need a @remindme

**Comment by louwers** [comment]
@matbee-eth Reminder. 🙂 What is customopfs?
