### ISSUE TITLE
ENOENT when calling stat on directory with slash at the end 

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/lightning-fs#13]
I'm trying to use my old service worker for server like file access but it don't work with lightingFS because:
```
fs.stat('/foo/', (e) => { console.log(e)});
```
show error:
```
ENOENT: /foo/
```

the directory exists because `fs.stat('/foo', ...)` is working fine.

I need this to be working because I'm distinguishing directories from files using slash at the end of the directory. Probably my worker can be refactored but it would be nice if the library work the same as Node fs.

**Comment by wmhilton** [comment]
> it would be nice if the library work the same as Node fs.

node's path module does a LOT of crazy things... and I intentionally kept my `path.js` module extremely lean. Buuuut I think we can squeeze in this little feature. :)

**Comment by jcubic** [comment]
I think that issue can be closed. Need to retest.
