### ISSUE TITLE
fs.rmdir(): expected a function but got undefined

### ISSUE THREAD

**Issue by ghost** [isomorphic-git/lightning-fs#20]
target: browser as defined in https://isomorphic-git.org/docs/en/browser

**Comment by wmhilton** [comment]
The callback argument is not optional. This is consistent with node, which requires callback functions.

![image](https://user-images.githubusercontent.com/587740/61245483-960e0400-a71a-11e9-97bc-696037a55f28.png)

Admittedly... node has a better error message. :/
