### ISSUE TITLE
Can we support Cloudflare KV store?

### ISSUE THREAD

**Issue by geekodour** [isomorphic-git/lightning-fs#27]
If you think this is possible, I'll be happy to work on this. or help you work on this.

https://developers.cloudflare.com/workers/reference/storage/overview/

**Comment by geekodour** [comment]
I also posted a relevant question here: https://community.cloudflare.com/t/indexdb-with-cloudflare-workers-for-using-git-in-workers/114813

**Comment by wmhilton** [comment]
that... would be interesting. I don't have the bandwidth to do it myself but if you figure out how to do it in a fork I might accept a PR. That's a really intriguing use case.

**Comment by iliasbhal** [comment]
`KV achieves this performance by being eventually-consistent.` ( may take up to 60 sec to reach consistency ).
an eventually consistent file system is something that is not acceptable in my opinion. 😞
