### ISSUE TITLE
Compressed data

### ISSUE THREAD

**Issue by agentcooper** [isomorphic-git/lightning-fs#29]
Hey. Do you have any experience using compressed data (like zip) with lightning-fs? My use case involves sending quite large file tree from the server and I want it to be synchronously available on the client. BrowserFS has [ZipFS](https://github.com/jvilk/BrowserFS/blob/master/src/backend/ZipFS.ts).

**Comment by wmhilton** [comment]
Nope, sorry. I got zero experience there.
