### ISSUE TITLE
fs.rename

### ISSUE THREAD

**Issue by FranzSkuffka** [isomorphic-git/lightning-fs#55]
`fs.rename` would be great and I imagine it might not be super trick to implement.

Is a PR welcome? I understand you would like to keep the API slim.

**Comment by amxmln** [comment]
I’m not sure if it was added after this issue was created, but the Readme mentions a `fs.rename` function, which is also present in the source code.

Or am I getting something wrong / confused here?

**Comment by FranzSkuffka** [comment]
You are right, i was mistaken.

I was reading the wrong documentation: https://isomorphic-git.org/docs/en/fs#using-the-promise-api-preferred

It is mentioned before the actual documentation. I personally think the docs can be improved by moving the API docs before the motivation etc. or providing a little table of contents.
