### ISSUE TITLE
Data Serialisation

### ISSUE THREAD

**Issue by jo** [isomorphic-git/lightning-fs#7]
Hmmm, that doesn't look right:

![screenshot from 2019-03-06 00-13-32](https://user-images.githubusercontent.com/17586/53844082-f048cc80-3fa4-11e9-9dd1-6e6711a8abb4.png)

Firefox,

```json
{
  "@isomorphic-git/lightning-fs": "^3.0.3",
  "isomorphic-git": "^0.51.12"
}
```

I use webpack to bundle for the browser.

**Comment by wmhilton** [comment]
That's a bug in Firefox DevTools the way it is presenting the data. It actually is working correctly... "!root" is an ES6 `Map` (not an empty object) and things wouldn't work at _all_ when you refreshed the page if it wasn't being deserialized correctly.

**Comment by jo** [comment]
ok thanks!
